# Generated by Django 4.1.5 on 2023-11-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_remove_trafficdata_data_trafficdata_average_speed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thing',
            new_name='Permissions',
        ),
    ]
