# Generated by Django 4.1.5 on 2023-11-26 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_rename_thing_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='virtual_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic.virtualdevice'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
